---
- name: assert supported system
  assert:
    that:
      - ansible_system == "Linux"
    fail_msg: "{{ ansible_system }} not supported"
    quiet: yes

- include_tasks: "{{ ansible_system | lower }}.yml"
