---
- name: assert supported distribution
  assert:
    that:
      - ansible_distribution == "Ubuntu"
    fail_msg: "{{ ansible_distribution }} not supported"
    quiet: yes

- include_tasks: "{{ ansible_distribution | lower }}.yml"
