---
# ansible-playbook -K -i localhost, playbook.yml

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - role: go
      version: latest
      arch: amd64
      prefix: /usr/local
      bindir: /usr/local/bin
