---
- name: install build-essential, curl, git, htop, vim
  become: yes
  apt:
    name:
      - build-essential
      - curl
      - git
      - htop
      - vim
    state: latest
    update_cache: yes
